### GENERAL SETTINGS ###

# Site settings
title: ELECTRIC MIX OPTIMIZATION
description: "Spanish electric mix optimizations for 2030, 2040 and 2050 applying artificial intelligence techniques"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
# ------ #
# GitHub #
# ------ #
baseurl: "/mix_optimizations" #important: start with /
url: "javibonilla.github.io"
# --- #
# PSA #
# --- #
# baseurl: ""
# url: "mixspain.psa.es"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#50c680" #"#F70031"
  primary_rgb: "80,198,128" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#35373c" #"#33004D"
  link: "#50c680"
  link_hover: "#67ffa4"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/
  results:
    output: true
    permalink: /results
  emissions:
    output: true
    parmalink: /emissions
  emissions_2018:
    output: true
    parmalink: /emissions_2018

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  # - title: dribbble
  #  url:
  - title: facebook
    url: https://www.facebook.com/plataformasolardealmeria
  - title: twitter
    url: https://twitter.com/psaciemat
  - title: website
    url: https://www.psa.es/en
  # - title: tumblr
  #  url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Plataforma Solar de Almería
    - Ctra. de Senés km. 4,5 Tabernas,
    - Almería, Spain.
email: info@psa.es
tel: +34 950 387 800
version: "0.6.5"


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
# members:
#   - name: Mark Webber
#     position: CEO
#     text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#     img: team01.jpg
#     social:
#       - title: envelope #use for email address
#         url: mailto:name@domain.com
#       - title: twitter
#         url: http://twitter.com/handle
#   - name: Paul Jameson
#     position: Lead Designer
#     text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#     img: team02.jpg
#     social:
#       - title: envelope #use for email address
#         url: mailto:name@domain.com
#       - title: twitter
#         url: http://twitter.com/handle
#   - name: Laura Sommers
#     position: Lead Developer
#     text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#     img: team03.jpg
#     social:
#       - title: envelope #use for email address
#         url: mailto:name@domain.com
#       - title: twitter
#         url: http://twitter.com/handle
#   - name: Martin Blunt
#     position: Marketing
#     text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#     img: team04.jpg
#     social:
#       - title: envelope #use for email address
#         url: mailto:name@domain.com
#       - title: twitter
#         url: http://twitter.com/handle

# Clients information. Shown on Home and About pages.
# clients:
#   - name: dribbble
#     img: client01.png
#   - name: Code is Poetry
#     img: client02.png
#   - name: Vimeo
#     img: client03.png
#   - name: VimeoPro
#     img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Plataforma Solar de Almería (PSA), a dependency of CIEMAT, is the largest concentrating solar technology research, development and test center in Europe. PSA activities are integrated in the CIEMAT organization as an R&D division of the Department of Energy."

# Testimonial content. Shown on Home and About page.
# testimonial:
#     message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
#     author: Marcel Newman
#     position: WEB DESIGNER - BLACKTIE.CO
